import * as fs from "fs";
import * as path from "path";

const ICONS_DIR = path.join(__dirname, "../src/assets/icons");
const OUTPUT_DIR = path.join(__dirname, "../src/components/icons");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "generated.ts");
const TYPES_FILE = path.join(OUTPUT_DIR, "types.ts");

interface IconInfo {
  name: string; // account, database-upload
  variant: string; // fill, outline
  size: number; // 16, 20, 24
  fileName: string; // icon_account_fill_16.svg
  componentName: string; // IconAccountFill16
}

function parseIconFileName(fileName: string): IconInfo | null {
  // Pattern: icon_<name>_<variant>_<size>.svg
  const match = fileName.match(/^icon_(.+)_(fill|outline)_(\d+)\.svg$/);
  if (!match) return null;

  const [, namePart, variant, sizeStr] = match;
  const size = parseInt(sizeStr, 10);

  // Convert kebab-case and spaces to PascalCase
  // database-upload -> DatabaseUpload
  // close full screen -> CloseFullScreen
  const componentNamePart = namePart
    .split(/[-_\s]/)
    .filter((word) => word.length > 0)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");

  const variantPart = variant.charAt(0).toUpperCase() + variant.slice(1);
  const componentName = `Icon${componentNamePart}${variantPart}${size}`;

  return {
    name: namePart,
    variant,
    size,
    fileName,
    componentName,
  };
}

function generateIcons() {
  console.log("🔍 Scanning icons directory...");

  const files = fs.readdirSync(ICONS_DIR);
  const icons: IconInfo[] = [];

  for (const file of files) {
    if (!file.endsWith(".svg")) continue;

    const iconInfo = parseIconFileName(file);
    if (iconInfo) {
      icons.push(iconInfo);
    } else {
      console.warn(`⚠️  Skipping invalid file name: ${file}`);
    }
  }

  console.log(`✅ Found ${icons.length} icons`);

  // Sort by component name
  icons.sort((a, b) => a.componentName.localeCompare(b.componentName));

  // Generate exports file
  const exports = icons
    .map(
      (icon) =>
        `export { default as ${icon.componentName} } from '../../assets/icons/${icon.fileName}?react';`
    )
    .join("\n");

  const generatedContent = `// This file is auto-generated by scripts/generate-icons.ts
// Do not edit manually

${exports}
`;

  // Generate types
  const iconNames = Array.from(new Set(icons.map((i) => i.name))).sort();
  const variants = Array.from(new Set(icons.map((i) => i.variant))).sort();
  const sizes = Array.from(new Set(icons.map((i) => i.size))).sort();
  const componentNames = icons.map((i) => `'${i.componentName}'`).join(" | ");

  const typesContent = `// This file is auto-generated by scripts/generate-icons.ts
// Do not edit manually

export type IconName = ${iconNames.map((n) => `'${n}'`).join(" | ")};

export type IconVariant = ${variants.map((v) => `'${v}'`).join(" | ")};

export type IconSize = ${sizes.join(" | ")};

export type IconComponentName = ${componentNames};

export interface IconMetadata {
  name: IconName;
  variant: IconVariant;
  size: IconSize;
  componentName: IconComponentName;
}

export const ICON_METADATA: IconMetadata[] = ${JSON.stringify(
    icons.map((i) => ({
      name: i.name,
      variant: i.variant,
      size: i.size,
      componentName: i.componentName,
    })),
    null,
    2
  )};
`;

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Write files
  fs.writeFileSync(OUTPUT_FILE, generatedContent, "utf-8");
  fs.writeFileSync(TYPES_FILE, typesContent, "utf-8");

  console.log(`✅ Generated ${OUTPUT_FILE}`);
  console.log(`✅ Generated ${TYPES_FILE}`);
  console.log(`📦 Total icons: ${icons.length}`);
  console.log(`📛 Unique names: ${iconNames.length}`);
  console.log(`🎨 Variants: ${variants.join(", ")}`);
  console.log(`📏 Sizes: ${sizes.join(", ")}`);
}

generateIcons();
